library(plyr)
library(reshape2)
features <- read.table("features.txt", header = FALSE)
activities <- read.table("activity_labels.txt", header = FALSE)
colnames(features) <- c("featureID", "featureName")
test_x <- read.table("X_test.txt", header = FALSE, col.names = features$featureName)
test_y <- read.table("y_test.txt", header = FALSE)
test_subject <- read.table("subject_test.txt", header = FALSE)
train_x <- read.table("X_train.txt", header = FALSE, col.names = features$featureName)
train_y <- read.table("y_train.txt", header = FALSE)
train_subject <- read.table("subject_train.txt", header = FALSE)
x <- rbind(test_x, train_x)
y <- rbind(test_y, train_y)
subject <- rbind(test_subject, train_subject)

combined <- cbind(subject, y, x)
colnames(combined)[1:2] <- c("subject","actID")
combinedWithNamedActivities <- merge(activities, combined, by.x = 1, by.y = 2, sort = FALSE)
colnames(combinedWithNamedActivities)[1:2] <- c("actID","action")
subsetColumns <- grep("(subject|action|mean|std)",colnames(combinedWithNamedActivities))
subset <- combinedWithNamedActivities[,subsetColumns]
averagePerSubjectAndAction <- ddply(subset, c("subject","action"), numcolwise(mean))
write.table(averagePerSubjectAndAction, row.names=FALSE, file="newdataset.txt")

